import type { Metadata } from 'next'

import { montserrat, titilliumWeb } from 'styles/fonts'
import './globals.css'
import 'styles/index.scss'

export const metadata: Metadata = {
  title: 'Teste Técnico da Maeztra',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${titilliumWeb.variable} ${montserrat.variable}`}>
        {children}
      </body>
    </html>
  )
}
